version: "3"
services:
  mongodb:
    image: mongo:6.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
volumes:
  mongodb_data:
